// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"

export interface CaluculateRouteResponse {
  formatVersion: string;
  routes:        Route[];
}

export interface Route {
  summary:  Summary;
  legs:     Leg[];
  sections: Section[];
}

export interface Leg {
  summary: Summary;
  points:  Point[];
}

export interface Point {
  latitude:  number;
  longitude: number;
}

export interface Summary {
  lengthInMeters:        number;
  travelTimeInSeconds:   number;
  trafficDelayInSeconds: number;
  trafficLengthInMeters: number;
  departureTime:         string;
  arrivalTime:           string;
}

export interface Section {
  startPointIndex: number;
  endPointIndex:   number;
  sectionType:     string;
  travelMode:      string;
}
